### ISSUE TITLE
Throw configuration exception if api key does not start with "NRII-"

### ISSUE THREAD

**Issue by twaremike** [newrelic/newrelic-telemetry-sdk-dotnet#147] opened 2020-10-20 22:17 UTC
## Summary

It's too easy for users new to NewRelic to be confused given the number of different api keys, and waste hours thinking their code is wrong because the exporter by default does not show any indication that there's an authentication problem. Also it's not apparent that you must not use the rest api key, and instead must exit the one portal to the insights portal to generate a key there.

## Desired Behaviour

if NewRelicExporterOptions.ApiKey does not begin with "NRII-", a configuration exception should be thrown.

**Comment by nrcventura** [comment] 2020-10-20 22:44
@elucus is this something that we can and should be doing?

**Comment by elucus** [comment] 2020-10-23 22:54
I've created a #153 to make it clear in the examples and documentation that you need to use an Insights Insert API key.

@justinfoote seems like the overall issue of having multiple key types spans all agents. Is there anything we should do here?

**Comment by justinfoote** [comment] 2020-10-25 17:21
Yes, we should do something here, and we actually have some work in progress to unify the experience around these keys, and to simplify the configuration of telemetry SDKs (and the integrations based on them).

Unfortunately, it's not as simple as checking that the API key begins with `NRII`. Until about a year ago, New Relic's insert keys did not start with a consistent prefix. And any customer who created their key before that point still has a valid working key without the prefix.

**Comment by twaremike** [comment] 2020-10-26 20:27
@justinfoote makes sense. Perhaps a config error could be raised if it's known bad key format, i.e. it begins with "NRRA-". Other than that feel free to close this.

**Comment by ebuckley23** [comment] 2020-11-20 04:34
@elucus appreciate #153 because it got me a lot closer to the root cause of my problem as I was using a REST api key as well. The link to creating an Insights key is not in the most obvious location and the documentation appears to be slightly outdated

**Comment by elucus** [comment] 2021-01-05 18:23
I'm going to close this issue because we have a work in progress to accept either the Insert API key or license key.

**Closed by elucus** 2021-01-05 18:23 UTC
Labels: enhancement
